--------------------------------------------------------
--  文件已创建 - 星期六-十一月-30-2019   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table SYS_AUTHORITY
--------------------------------------------------------

  CREATE TABLE "EZNEW"."SYS_AUTHORITY" 
   (	"SYSNO" NUMBER(19,0), 
	"CODE" VARCHAR2(50 CHAR), 
	"NAME" VARCHAR2(50 CHAR), 
	"AUTHORITYTYPE" NUMBER(10,0), 
	"STATUS" NUMBER(10,0), 
	"SORT" NUMBER(10,0), 
	"GROUP_" NUMBER(19,0) DEFAULT (0), 
	"REMARK" VARCHAR2(50 CHAR), 
	"CREATEDATE" DATE DEFAULT SYSDATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
 

   COMMENT ON COLUMN "EZNEW"."SYS_AUTHORITY"."CODE" IS '权限编码';
 
   COMMENT ON COLUMN "EZNEW"."SYS_AUTHORITY"."NAME" IS '名称';
 
   COMMENT ON COLUMN "EZNEW"."SYS_AUTHORITY"."AUTHORITYTYPE" IS '权限类型';
 
   COMMENT ON COLUMN "EZNEW"."SYS_AUTHORITY"."STATUS" IS '状态';
 
   COMMENT ON COLUMN "EZNEW"."SYS_AUTHORITY"."SORT" IS '排序';
 
   COMMENT ON COLUMN "EZNEW"."SYS_AUTHORITY"."GROUP_" IS '权限分组';
 
   COMMENT ON COLUMN "EZNEW"."SYS_AUTHORITY"."REMARK" IS '说明';
 
   COMMENT ON COLUMN "EZNEW"."SYS_AUTHORITY"."CREATEDATE" IS '添加时间';
 
   COMMENT ON TABLE "EZNEW"."SYS_AUTHORITY"  IS '权限';
--------------------------------------------------------
--  DDL for Table SYS_AUTHORITYBINDOPERATION
--------------------------------------------------------

  CREATE TABLE "EZNEW"."SYS_AUTHORITYBINDOPERATION" 
   (	"AUTHORITYOPERATIONSYSNO" NUMBER(19,0) DEFAULT (0), 
	"AUTHORITYSYSNO" NUMBER(19,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
 

   COMMENT ON COLUMN "EZNEW"."SYS_AUTHORITYBINDOPERATION"."AUTHORITYOPERATIONSYSNO" IS '授权操作编号';
 
   COMMENT ON COLUMN "EZNEW"."SYS_AUTHORITYBINDOPERATION"."AUTHORITYSYSNO" IS '权限编号';
 
   COMMENT ON TABLE "EZNEW"."SYS_AUTHORITYBINDOPERATION"  IS '权限&授权操作关联';
--------------------------------------------------------
--  DDL for Table SYS_AUTHORITYGROUP
--------------------------------------------------------

  CREATE TABLE "EZNEW"."SYS_AUTHORITYGROUP" 
   (	"SYSNO" NUMBER(19,0), 
	"NAME" VARCHAR2(50 CHAR), 
	"SORT" NUMBER(10,0), 
	"STATUS" NUMBER(10,0), 
	"PARENT" NUMBER(19,0) DEFAULT (0), 
	"LEVEL_" NUMBER(10,0) DEFAULT (0), 
	"REMARK" VARCHAR2(100 CHAR)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
 

   COMMENT ON COLUMN "EZNEW"."SYS_AUTHORITYGROUP"."SYSNO" IS '编号';
 
   COMMENT ON COLUMN "EZNEW"."SYS_AUTHORITYGROUP"."NAME" IS '名称';
 
   COMMENT ON COLUMN "EZNEW"."SYS_AUTHORITYGROUP"."SORT" IS '排序';
 
   COMMENT ON COLUMN "EZNEW"."SYS_AUTHORITYGROUP"."STATUS" IS '状态';
 
   COMMENT ON COLUMN "EZNEW"."SYS_AUTHORITYGROUP"."PARENT" IS '上级分组';
 
   COMMENT ON COLUMN "EZNEW"."SYS_AUTHORITYGROUP"."LEVEL_" IS '分组等级';
 
   COMMENT ON COLUMN "EZNEW"."SYS_AUTHORITYGROUP"."REMARK" IS '说明';
 
   COMMENT ON TABLE "EZNEW"."SYS_AUTHORITYGROUP"  IS '权限分组';
--------------------------------------------------------
--  DDL for Table SYS_AUTHORITYOPERATION
--------------------------------------------------------

  CREATE TABLE "EZNEW"."SYS_AUTHORITYOPERATION" 
   (	"SYSNO" NUMBER(19,0) DEFAULT (0), 
	"CONTROLLERCODE" VARCHAR2(100 CHAR), 
	"ACTIONCODE" VARCHAR2(100 CHAR), 
	"NAME" VARCHAR2(50 CHAR), 
	"STATUS" NUMBER(10,0) DEFAULT (0), 
	"SORT" NUMBER(10,0) DEFAULT (0), 
	"GROUP_" NUMBER(19,0) DEFAULT (0), 
	"AUTHORIZETYPE" NUMBER(10,0) DEFAULT (0), 
	"REMARK" VARCHAR2(50 CHAR)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
 

   COMMENT ON COLUMN "EZNEW"."SYS_AUTHORITYOPERATION"."SYSNO" IS '主键编号';
 
   COMMENT ON COLUMN "EZNEW"."SYS_AUTHORITYOPERATION"."CONTROLLERCODE" IS '控制器';
 
   COMMENT ON COLUMN "EZNEW"."SYS_AUTHORITYOPERATION"."ACTIONCODE" IS '操作方法';
 
   COMMENT ON COLUMN "EZNEW"."SYS_AUTHORITYOPERATION"."NAME" IS '名称';
 
   COMMENT ON COLUMN "EZNEW"."SYS_AUTHORITYOPERATION"."STATUS" IS '状态';
 
   COMMENT ON COLUMN "EZNEW"."SYS_AUTHORITYOPERATION"."SORT" IS '排序';
 
   COMMENT ON COLUMN "EZNEW"."SYS_AUTHORITYOPERATION"."GROUP_" IS '操作分组';
 
   COMMENT ON COLUMN "EZNEW"."SYS_AUTHORITYOPERATION"."AUTHORIZETYPE" IS '授权类型';
 
   COMMENT ON COLUMN "EZNEW"."SYS_AUTHORITYOPERATION"."REMARK" IS '方法描述';
 
   COMMENT ON TABLE "EZNEW"."SYS_AUTHORITYOPERATION"  IS '授权操作';
--------------------------------------------------------
--  DDL for Table SYS_AUTHORITYOPERATIONGROUP
--------------------------------------------------------

  CREATE TABLE "EZNEW"."SYS_AUTHORITYOPERATIONGROUP" 
   (	"SYSNO" NUMBER(19,0) DEFAULT (0), 
	"NAME" VARCHAR2(50 CHAR), 
	"SORT" NUMBER(10,0) DEFAULT (0), 
	"PARENT" NUMBER(19,0) DEFAULT (0), 
	"LEVEL_" NUMBER(10,0) DEFAULT (0), 
	"STATUS" NUMBER(10,0) DEFAULT (0), 
	"REMARK" VARCHAR2(50 CHAR)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
 

   COMMENT ON COLUMN "EZNEW"."SYS_AUTHORITYOPERATIONGROUP"."SYSNO" IS '编号';
 
   COMMENT ON COLUMN "EZNEW"."SYS_AUTHORITYOPERATIONGROUP"."NAME" IS '名称';
 
   COMMENT ON COLUMN "EZNEW"."SYS_AUTHORITYOPERATIONGROUP"."SORT" IS '排序';
 
   COMMENT ON COLUMN "EZNEW"."SYS_AUTHORITYOPERATIONGROUP"."PARENT" IS '上级';
 
   COMMENT ON COLUMN "EZNEW"."SYS_AUTHORITYOPERATIONGROUP"."LEVEL_" IS '等级';
 
   COMMENT ON COLUMN "EZNEW"."SYS_AUTHORITYOPERATIONGROUP"."STATUS" IS '状态';
 
   COMMENT ON COLUMN "EZNEW"."SYS_AUTHORITYOPERATIONGROUP"."REMARK" IS '说明';
 
   COMMENT ON TABLE "EZNEW"."SYS_AUTHORITYOPERATIONGROUP"  IS '授权操作组';
--------------------------------------------------------
--  DDL for Table SYS_ROLE
--------------------------------------------------------

  CREATE TABLE "EZNEW"."SYS_ROLE" 
   (	"SYSNO" NUMBER(19,0), 
	"NAME" VARCHAR2(50 CHAR), 
	"LEVEL_" NUMBER(10,0), 
	"PARENT" NUMBER(19,0), 
	"SORT" NUMBER(10,0), 
	"STATUS" NUMBER(10,0), 
	"CREATEDATE" DATE, 
	"REMARK" VARCHAR2(50 CHAR)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
 

   COMMENT ON COLUMN "EZNEW"."SYS_ROLE"."SYSNO" IS '角色编号';
 
   COMMENT ON COLUMN "EZNEW"."SYS_ROLE"."NAME" IS '名称';
 
   COMMENT ON COLUMN "EZNEW"."SYS_ROLE"."LEVEL_" IS '等级';
 
   COMMENT ON COLUMN "EZNEW"."SYS_ROLE"."PARENT" IS '上级';
 
   COMMENT ON COLUMN "EZNEW"."SYS_ROLE"."SORT" IS '排序';
 
   COMMENT ON COLUMN "EZNEW"."SYS_ROLE"."STATUS" IS '状态';
 
   COMMENT ON COLUMN "EZNEW"."SYS_ROLE"."CREATEDATE" IS '添加时间';
 
   COMMENT ON COLUMN "EZNEW"."SYS_ROLE"."REMARK" IS '备注信息';
 
   COMMENT ON TABLE "EZNEW"."SYS_ROLE"  IS '角色';
--------------------------------------------------------
--  DDL for Table SYS_ROLEAUTHORIZE
--------------------------------------------------------

  CREATE TABLE "EZNEW"."SYS_ROLEAUTHORIZE" 
   (	"ROLESYSNO" NUMBER(19,0), 
	"AUTHORITYSYSNO" NUMBER(19,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
 

   COMMENT ON COLUMN "EZNEW"."SYS_ROLEAUTHORIZE"."ROLESYSNO" IS '角色编号';
 
   COMMENT ON COLUMN "EZNEW"."SYS_ROLEAUTHORIZE"."AUTHORITYSYSNO" IS '权限编号';
 
   COMMENT ON TABLE "EZNEW"."SYS_ROLEAUTHORIZE"  IS '角色权限';
--------------------------------------------------------
--  DDL for Table SYS_USER
--------------------------------------------------------

  CREATE TABLE "EZNEW"."SYS_USER" 
   (	"SYSNO" NUMBER(19,0), 
	"USERNAME" VARCHAR2(50 CHAR), 
	"REALNAME" VARCHAR2(50 CHAR), 
	"PWD" VARCHAR2(50 CHAR), 
	"USERTYPE" NUMBER(10,0), 
	"STATUS" NUMBER(10,0), 
	"MOBILE" VARCHAR2(15 CHAR), 
	"EMAIL" VARCHAR2(50 CHAR), 
	"QQ" VARCHAR2(15 CHAR), 
	"SUPERUSER" NUMBER(1,0), 
	"CREATEDATE" DATE, 
	"LASTLOGINDATE" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
 

   COMMENT ON COLUMN "EZNEW"."SYS_USER"."SYSNO" IS '用户编号';
 
   COMMENT ON COLUMN "EZNEW"."SYS_USER"."USERNAME" IS '用户名';
 
   COMMENT ON COLUMN "EZNEW"."SYS_USER"."REALNAME" IS '真实名称';
 
   COMMENT ON COLUMN "EZNEW"."SYS_USER"."PWD" IS '密码';
 
   COMMENT ON COLUMN "EZNEW"."SYS_USER"."USERTYPE" IS '类型';
 
   COMMENT ON COLUMN "EZNEW"."SYS_USER"."STATUS" IS '状态';
 
   COMMENT ON COLUMN "EZNEW"."SYS_USER"."MOBILE" IS '手机';
 
   COMMENT ON COLUMN "EZNEW"."SYS_USER"."EMAIL" IS '邮箱';
 
   COMMENT ON COLUMN "EZNEW"."SYS_USER"."QQ" IS 'QQ';
 
   COMMENT ON COLUMN "EZNEW"."SYS_USER"."SUPERUSER" IS '超级管理员';
 
   COMMENT ON COLUMN "EZNEW"."SYS_USER"."CREATEDATE" IS '添加时间';
 
   COMMENT ON COLUMN "EZNEW"."SYS_USER"."LASTLOGINDATE" IS '最近登录时间';
 
   COMMENT ON TABLE "EZNEW"."SYS_USER"  IS '管理用户';
--------------------------------------------------------
--  DDL for Table SYS_USERAUTHORIZE
--------------------------------------------------------

  CREATE TABLE "EZNEW"."SYS_USERAUTHORIZE" 
   (	"USERSYSNO" NUMBER(19,0), 
	"AUTHORITYSYSNO" NUMBER(19,0), 
	"DISABLE" NUMBER(1,0) DEFAULT (1)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
 

   COMMENT ON COLUMN "EZNEW"."SYS_USERAUTHORIZE"."USERSYSNO" IS '用户';
 
   COMMENT ON COLUMN "EZNEW"."SYS_USERAUTHORIZE"."AUTHORITYSYSNO" IS '权限';
 
   COMMENT ON COLUMN "EZNEW"."SYS_USERAUTHORIZE"."DISABLE" IS '禁用';
 
   COMMENT ON TABLE "EZNEW"."SYS_USERAUTHORIZE"  IS '用户授权';
--------------------------------------------------------
--  DDL for Table SYS_USERLOGINRECORD
--------------------------------------------------------

  CREATE TABLE "EZNEW"."SYS_USERLOGINRECORD" 
   (	"SYSNO" NUMBER(19,0), 
	"USERSYSNO" NUMBER(19,0), 
	"LOGINDATE" DATE, 
	"IP" VARCHAR2(30 CHAR), 
	"ADDRESS" VARCHAR2(50 CHAR)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
 

   COMMENT ON COLUMN "EZNEW"."SYS_USERLOGINRECORD"."SYSNO" IS '编号';
 
   COMMENT ON COLUMN "EZNEW"."SYS_USERLOGINRECORD"."USERSYSNO" IS '登录用户编号';
 
   COMMENT ON COLUMN "EZNEW"."SYS_USERLOGINRECORD"."LOGINDATE" IS '登录时间';
 
   COMMENT ON COLUMN "EZNEW"."SYS_USERLOGINRECORD"."IP" IS '登陆IP地址';
 
   COMMENT ON COLUMN "EZNEW"."SYS_USERLOGINRECORD"."ADDRESS" IS '登陆地址';
 
   COMMENT ON TABLE "EZNEW"."SYS_USERLOGINRECORD"  IS '用户登录记录';
--------------------------------------------------------
--  DDL for Table SYS_USERROLE
--------------------------------------------------------

  CREATE TABLE "EZNEW"."SYS_USERROLE" 
   (	"USERSYSNO" NUMBER(19,0), 
	"ROLESYSNO" NUMBER(19,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
 

   COMMENT ON COLUMN "EZNEW"."SYS_USERROLE"."USERSYSNO" IS '用户';
 
   COMMENT ON COLUMN "EZNEW"."SYS_USERROLE"."ROLESYSNO" IS '角色';
 
   COMMENT ON TABLE "EZNEW"."SYS_USERROLE"  IS '用户角色';
   
--------------------------------------------------------
--  DDL for CREATE DEFAULT USER
--------------------------------------------------------
   
   INSERT INTO Sys_User (SysNo, UserName, RealName, Pwd, UserType, Status, Mobile, Email, QQ, SuperUser, CreateDate, LastLoginDate) VALUES (65464646465461, 'admin', 'EZNEW', '21232f297a57a5a743894a0e4a801fc3', 210, 310, '13612345678', 'admin@eznew.net', '1231278', 1, to_date('2017-05-31','yyyy-MM-dd'), to_date('2017-05-31','yyyy-MM-dd'));
   Commit;